const multer = require('multer');
const SystemCharacter = require('../models/systemCharacterModel');
const System = require('../models/systemModel');
const Ability = require('../models/abilityModel');
const AppError = require('../utils/appError');
const catchAsync = require('../utils/catchAsync');
const factory = require('./handlerFactory');

const multerStorage = multer.diskStorage({
  destination: (req, file, cb) => {
    cb(null, 'public/img/systems');
  },
  filename: (req, file, cb) => {
    const ext = file.mimetype.split('/')[1];
    const filename = `system-background-${
      req.params.sectionSlug
    }-${Date.now()}.${ext}`;
    cb(null, filename);
  }
});

const multerFilter = (req, file, cb) => {
  if (file.mimetype.startsWith('image')) {
    cb(null, true);
  } else {
    cb(new AppError('Not an image! Please upload only images.', 400), false);
  }
};

const upload = multer({
  storage: multerStorage,
  fileFilter: multerFilter
});

exports.uploadBackgroundImage = upload.single('backgroundImage');

exports.getSystemNavigation = catchAsync(async (req, res, next) => {
  const system = await System.findOne({ slug: req.params.systemSlug }).select(
    'name character slug id'
  );

  if (!system) return next(new AppError('No System found with that Slug', 404));

  const navigation = [
    {
      name: 'Roles',
      slug: 'roles',
      children: system.character.roles.map(role => ({
        name: role.name,
        slug: role.slug
      }))
    },
    {
      name: 'Races',
      slug: 'races',
      children: system.character.races.map(race => ({
        name: race.name,
        slug: race.slug
      }))
    }
  ];

  res.status(200).json({
    status: 'success',
    data: {
      system: system.name,
      systemSlug: system.slug,
      systemId: system.id,
      navigation
    }
  });
});

exports.getSystemCharacter = catchAsync(async (req, res, next) => {
  const query = await System.findById(req.params.systemId).select(
    'name id character'
  );

  const doc = await query;
  if (!doc) return next(new AppError('No System found with that Slug', 404));

  res.status(200).json({
    status: 'success',
    data: {
      breadcrumbs: {
        system: {
          name: doc.name,
          id: doc.id
        }
      },
      character: doc.character
    }
  });
});

exports.getSystemIntroduction = catchAsync(async (req, res, next) => {
  const doc = await System.findOne({ slug: req.params.systemSlug });

  if (!doc) return next(new AppError('No System found with that Slug', 404));

  res.status(200).json({
    status: 'success',
    data: { test: doc }
  });
});

exports.getAllSystems = factory.getAll(System);
// exports.getSystem = factory.getOne(System);

exports.getSystem = catchAsync(async (req, res, next) => {
  const system = await System.findOne({ slug: req.params.systemSlug });
  if (!system) return next(new AppError('No System found with that Slug', 404));

  res.status(200).json({
    status: 'success',
    data: system
  });
});

exports.createSystem = catchAsync(async (req, res, next) => {
  const { abilities, ...systemData } = req.body;

  // Create the system first
  const system = await System.create(systemData);

  // Handle abilities creation if provided
  if (abilities && Array.isArray(abilities)) {
    const abilityIds = [];
    
    for (let i = 0; i < abilities.length; i++) {
      const abilityData = abilities[i];
      if (abilityData.name && abilityData.name.trim()) {
        const ability = await Ability.create({
          name: abilityData.name.trim(),
          description: abilityData.description || '',
          system: system._id,
          order: abilityData.order !== undefined ? abilityData.order : i
        });
        abilityIds.push(ability._id);
      }
    }
    
    // Update system with ability references
    if (abilityIds.length > 0) {
      system.abilities = abilityIds;
      await system.save();
    }
  }

  // Populate abilities for response, sorted by order
  await system.populate({
    path: 'abilities',
    options: { sort: { order: 1 } }
  });

  res.status(201).json({
    status: 'success',
    data: system
  });
});

exports.updateSystem = catchAsync(async (req, res, next) => {
  const { characterUpdates, roles, races, abilities, ...systemUpdates } = req.body;
  
  // Slug will be automatically generated by the setSlug pre-hook

  if (req.file) {
    req.body.backgroundImage = req.file.filename;
  }

  // Handle abilities creation/update
  let abilityIds = [];
  if (abilities && Array.isArray(abilities)) {
    // First, find the system to get its ID
    const existingSystem = await System.findOne({ slug: req.params.systemSlug });
    if (!existingSystem) return next(new AppError('No System found with that Slug', 404));

    // Remove existing abilities for this system
    await Ability.deleteMany({ system: existingSystem._id });

    // Create new abilities
    for (let i = 0; i < abilities.length; i++) {
      const abilityData = abilities[i];
      if (abilityData.name && abilityData.name.trim()) {
        const ability = await Ability.create({
          name: abilityData.name.trim(),
          description: abilityData.description || '',
          system: existingSystem._id,
          order: abilityData.order !== undefined ? abilityData.order : i
        });
        abilityIds.push(ability._id);
      }
    }
    
    
    // Add abilities to system updates
    systemUpdates.abilities = abilityIds;
  }

  
  const system = await System.findOneAndUpdate(
    { slug: req.params.systemSlug },
    systemUpdates,
    {
      new: true,
      runValidators: true
    }
  ).populate({
    path: 'abilities',
    options: { sort: { order: 1 } }
  });

  if (!system) return next(new AppError('No System found with that Slug', 404));
  

  // if (system.character) {
  //   const characterUpdateFields = { ...characterUpdates };

  //   if (roles) {
  //     characterUpdateFields.roles = roles;
  //   }
  //   if (races) {
  //     characterUpdateFields.races = races;
  //   }

  //   await SystemCharacter.findByIdAndUpdate(
  //     system.character,
  //     characterUpdateFields,
  //     {
  //       new: true,
  //       runValidators: true
  //     }
  //   );
  // }

  // const updatedSystem = await System.findOne({
  //   slug: req.params.systemSlug
  // }).populate('character');

  res.status(200).json({
    status: 'success',
    data: system
  });
});

exports.deleteSystem = factory.deleteOne(System);
